version: '3.8'

services:
  omp_app:
    image: docker.io/bitnami/laravel
    restart: always
    container_name: omp_app
    ports:
      - 80:8000
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=secret
      - DB_DATABASE=omp_db
    volumes:
      - ../app:/app
    depends_on:
      - mysql
    networks:
      - mysql-network
  mysql:
    image: mysql:8.0.33
    restart: always
    container_name: mysql
    volumes:
      - ../storage/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: omp_db
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - mysql-network
networks:
  mysql-network:
    driver: bridge
